/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "outline": "#86948a",
        "on-surface": "#dde4dd",
        "secondary-fixed": "#c9e6ff",
        "secondary-fixed-dim": "#89ceff",
        "surface-container-high": "#242c27",
        "on-secondary": "#00344d",
        "surface-tint": "#4edea3",
        "secondary-container": "#00a2e6",
        "on-tertiary": "#650911",
        "error": "#ffb4ab",
        "primary-container": "#10b981",
        "secondary": "#89ceff",
        "primary-fixed-dim": "#4edea3",
        "surface-container-lowest": "#09100c",
        "on-tertiary-fixed-variant": "#842225",
        "on-primary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb3af",
        "tertiary-fixed": "#ffdad7",
        "error-container": "#93000a",
        "surface-variant": "#2f3632",
        "inverse-surface": "#dde4dd",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#005236",
        "surface-container-low": "#161d19",
        "on-tertiary-fixed": "#410005",
        "tertiary": "#ffb3af",
        "primary-fixed": "#6ffbbe",
        "on-primary-container": "#00422b",
        "tertiary-container": "#fc7c78",
        "surface-dim": "#0e1511",
        "surface-bright": "#343b36",
        "background": "#0e1511",
        "on-secondary-container": "#00344e",
        "on-primary": "#003824",
        "outline-variant": "#3c4a42",
        "inverse-primary": "#006c49",
        "on-secondary-fixed-variant": "#004c6e",
        "on-background": "#dde4dd",
        "inverse-on-surface": "#2b322d",
        "primary": "#4edea3",
        "surface-container-highest": "#2f3632",
        "on-surface-variant": "#bbcabf",
        "on-tertiary-container": "#711419",
        "surface-container": "#1a211d",
        "surface": "#0e1511",
        "on-secondary-fixed": "#001e2f"
      },
      fontFamily: {
        "data-mono": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "body-base": ["Inter"],
        "label-xs": ["Inter"],
        "display-lg": ["Inter"]
      }
    },
  },
  plugins: [],
}
